Action System, handle basic action implementation, setup verbs actions
ArchetypalTech/TheOrugginTrail pull request #60
Opened 2024-07-23 15:38 UTC by Dkrenon

I implemented the handle basic action in the **Action System**. Also I adjusted fetching the objects to use a normal array instead of the sized array. 
I added the kick action in the setup verbs action function as well the sniff action.
Added also a new case in the insult meat as it was done in the WE version.

If this PR is approved, don't delete the branch as there is another element that needs to be adjusted on the action system. I found out that if you do the complete action  (kick the ball to the window) and later do (burn the petrol at the stairs) after getting the petrol, the output will show both texts effects.

2024-07-24 16:37 UTC, lbdl requested changes
good stuff. I think we may be handling arrays wrong. We create them at a fixed size and I think that Solidity will 0 fill them? Im not sure about this but in these systems we populate the arrays from, calling function so therefore its SHOULD be safe to assume that if index 0 is 0 then so is the rest of the array and as such we can ignore

2024-07-24 16:37 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(ids)) {
this function `_arrayHasValidEntries` means we have to iterate through the entire array of 32, each time we check, better to just check if its not 0 length and doesnt have a ) entry as index 0. I think that because of the way Solidity is the len will always be non 0 though so we may not even need that check tbh but leave it for now unless you fund out something else

2024-07-24 16:37 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(sizedDids)) {
again dont use the function

2024-07-24 16:37 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +    function _arrayHasValidEntries(uint32[MAX_OBJ] memory arr) private pure returns (bool) {
I dont think we need this but if we do then just cjeck for no 0 len and non 0 index 0

2024-07-24 16:37 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(objs)) {
again not sure about this function

2024-07-24 16:37 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +    function countNonZero(uint32[MAX_OBJ] memory arr) private pure returns (uint32) {
this again is probably no use as all the arrays that we wil pass to it will have been populated by calling into the store, so even though the size is probablt non 0 because Solidity will init them with 0 values if index 0 is 0 then its empty for our purposes

2024-07-26 13:20 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(ids)) {
done

2024-07-26 13:20 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(sizedDids)) {
done

2024-07-26 13:20 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +    function _arrayHasValidEntries(uint32[MAX_OBJ] memory arr) private pure returns (bool) {
done

2024-07-26 13:20 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +        if (_arrayHasValidEntries(objs)) {
done

2024-07-26 13:20 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +    function countNonZero(uint32[MAX_OBJ] memory arr) private pure returns (uint32) {
done

2024-07-26 13:29 UTC, Dkrenon commented
In the **Action System**: it was fixed use of normal arrays. The functions `_arrayHasValidEntries` and `countNonZero` were removed as they were no needed at the end. The action output text was fixed (as we talked about it, it was cleared) at the `_getResponseStr` function.  
For fetching the object, it search first in the player's inventory if not there search's in the room. if the object is in the room and the player has other objects in his inventory, the action can be done. This solves the problem of having to have every object on either the player's inventory or in the room. 
Finished replacing the SizedArray with a "normal array".
In the **Tokeniser System** added some lines that allows to do the sniff action as it was not possible before.

2024-07-26 16:11 UTC, lbdl commented on packages/contracts/src/systems/ActionSystem.sol
> +                        if (objData.objectActionIds[j] != 0) {
can we be careful of these changes that are purely indentation, it makes far too much noise in the PR

2024-07-26 16:15 UTC, lbdl requested changes
minor grammer change. good work

2024-07-27 13:48 UTC, Dkrenon commented on packages/contracts/src/systems/GameSetupSystem.sol
>           uint32 throwDynamite = createAction(ActionType.Throw, "You throw quickly the dynamite\n"
Done

2024-07-27 13:48 UTC, Dkrenon commented on packages/contracts/src/systems/ActionSystem.sol
> +                        if (objData.objectActionIds[j] != 0) {
ok, will be more careful with them

2024-07-27 22:50 UTC, lbdl approved these changes

2024-07-27 22:51 UTC, merged